---
name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  # Changelog
  
  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'infrastructure'
      - 'automation'
      - 'documentation'
  - title: '🏎 Performance'
    label: 'performance'

version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'enhancement'
  patch:
    labels:
      - 'bug'
      - 'maintenance'
      - 'documentation'
  default: patch

autolabeler:
  - label: 'documentation'
    files:
      - '*.md'
    branch:
      - '/doc\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
  - label: 'github'
    files:
      - '.github/*'
  - label: 'configuration'
    files:
      - '**.yaml'
      - '**.json'
      - '.env'
