---
# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

APPLY_FIXES: none
LOG_LEVEL: INFO
VALIDATE_ALL_CODEBASE: false

# Reporters
EMAIL_REPORTER: false

DISABLE_LINTERS:
  - SPELL_LYCHEE
  - SPELL_CSPELL
  - REPOSITORY_CHECKOV
  - REPOSITORY_TRUFFLEHOG
