---
# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

APPLY_FIXES: none
LOG_LEVEL: WARNING
VALIDATE_ALL_CODEBASE: false
# Formatter errors will be reported as errors (and not warnings) if this variable is set to false
# FORMATTERS_DISABLE_ERRORS: false

# Reporters
EMAIL_REPORTER: false

DISABLE_LINTERS:
  - SPELL_LYCHEE
  - SPELL_CSPELL
  - REPOSITORY_CHECKOV
  - REPOSITORY_TRUFFLEHOG
