---
name: Release

###########################
# Start on push to main #
###########################
on:
  push:
    tags:
      - "*"

#################
# Start the job #
#################
permissions:
  contents: read

jobs:
  update-release-draft:
    permissions:
      contents: write # for release-drafter/release-drafter to create a github release
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
